# Generated by Django 4.2.7 on 2023-12-19 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0004_car_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='buyer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
